### ISSUE TITLE
GetFileSize - SIZE not allowed in ASCII mode

### ISSUE THREAD

**Issue by daantobk** [robinrodricks/FluentFTP#137]
The FTP server returns 'SIZE not allowed in ASCII mode'. But I cannot change the FtpDataType to Binary, since this is protected code.
Please help??

**Comment by hgupta9** [comment]
Try the latest. There are some fixes for ASCII

https://www.nuget.org/packages/FluentFTP/

**Comment by daantobk** [comment]
I tried, but still not working.
Response is still:
550 SIZE not allowed in ASCII mode

2 possible fixes: 
- set to binary mode in function GetFileSize
or
- make make function SetDataType(FtpDataType type) public

**Comment by hgupta9** [comment]
Try the latest. There are some fixes for this by rharrisxtheta.

https://www.nuget.org/packages/FluentFTP/

**Comment by hgupta9** [comment]
And which server are you using?

**Comment by daantobk** [comment]
Yes it works for version 17.5.8.
Thank you very much!

I don't know which server our client is using, because they don't send the version in the FTP session

**Comment by hgupta9** [comment]
Glad it works for you. Special thanks to @rharrisxtheta for the fix.

**Comment by Tekkion** [comment]
using 19.1.2 and it seems the error reappeared

**Comment by Blackleones** [comment]
same error on 26.0.1

**Comment by robinrodricks** [comment]
@Blackleones please check with this version?

https://we.tl/t-MUcikEcMsX

If you still get the error please send the logs so we can check (FAQ has steps how to get logs)

**Comment by robinrodricks** [comment]
@Tekkion @daantobk @Blackleones  Can one of you guys check the version I posted? I tried to fix this...

**Comment by robinrodricks** [comment]
Some fixes released in 26.0.2, please check:

https://www.nuget.org/packages/FluentFTP/26.0.2

If there are still issues, message here I'll reopen this thread.

**Comment by Blackleones** [comment]
@robinrodricks problem still in 26.0.2 

Status:   Connecting to ***
Response: 220 Aruba FTP2S3 gateway 1.0.1 ready.
Command:  USER ***
Response: 331 Username ok, send password.
Command:  PASS ***
Response: 230 Login successful.
Command:  FEAT
Response: 211 End FEAT.
Response: 211-Features supported:
Response: AUTH SSL
Response: AUTH TLS
Response: EPRT
Response: EPSV
Response: MDTM
Response: MFMT
Response: MLST type*;perm*;size*;modify*;unique*;unix.mode;unix.uid;unix.gid;
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: UTF8
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 501 Invalid argument.
Command:  SYST
Response: 215 UNIX Type: L8

# DirectoryExists("cmr/AA000ZZ/2019/12345679")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is the current directory.
Command:  CWD cmr/AA000ZZ/2019/12345679
Response: 250 "/cmr/AA000ZZ/2019/12345679" is the current directory.
Command:  CWD /
Response: 250 "/" is the current directory.

# SetWorkingDirectory("cmr/AA000ZZ/2019/12345679")
Command:  CWD cmr/AA000ZZ/2019/12345679
Response: 250 "/cmr/AA000ZZ/2019/12345679" is the current directory.

# FileExists("INFO.json")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/cmr/AA000ZZ/2019/12345679" is the current directory.
Command:  SIZE /cmr/AA000ZZ/2019/12345679/INFO.json
Response: 550 SIZE not allowed in ASCII mode.

**Comment by robinrodricks** [comment]
Hi can you please give the full logs... I've coded it to retry the moment it gets that error...

**Comment by robinrodricks** [comment]
@Blackleones Please send full logs

**Comment by emmanuelmathot** [comment]
I have a similar issue on an french FTP. GetFileSize method always returns -1
```
Text` encoding: System.Text.UTF8Encoding
InfoCommand:  OPTS UTF8 ON
VerboseResponse: 211-Features:
Response: MFF modify;UNIX.group;UNIX.mode;
Response: REST STREAM
Response: MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
Response: UTF8
Response: EPRT
Response: SITE SYMLINK
Response: EPSV
Response: SITE UTIME
Response: MDTM
Response: SITE RMDIR
Response: TVFS
Response: SITE COPY
Response: MFMT
Response: SIZE
Response: LANG fr-FR.UTF-8*;fr-FR
Response: SITE MKDIR
InfoResponse: 211 Fin
InfoStatus:   Text encoding: System.Text.UTF8Encoding
InfoCommand:  OPTS UTF8 ON
InfoResponse: 550 SIZE n'est pas autorisé en mode ASCII
```

Please note the response in french lang that probably affect the interpretation of the response.

**Comment by robinrodricks** [comment]
@emmanuelmathot  Please check : https://www.nuget.org/packages/FluentFTP/29.0.4

**Comment by patzila** [comment]
Hello I am getting a similar issue and having difficulties troubleshooting it. I am on version 30.0.0. I can read. I'm not sure what I can do or if I'm doing anything wrong. Any help will be much appreciated. :)

Here is the FTP Trace
```
# ConnectAsync()
Status:   Connecting to ***:21
Response: 220 Website FTP Server Ready
Command:  USER ***
Response: 331 Password required for <myuser>
Command:  PASS ***
Response: 230 User <myuser>logged in
Command:  FEAT
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: TVFS
Response: MFMT
Response: SIZE
Response: LANG fr-FR;zh-TW;ko-KR;zh-CN;ja-JP;en-US;bg-BG;ru-RU;it-IT;es-ES
Response: MFF modify;UNIX.group;UNIX.mode;
Response: REST STREAM
Response: MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
Response: UTF8
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 UTF8 set to on
Command:  SYST
Response: 215 UNIX Type: L8


# MoveFileAsync("/newEdiTest.edi", "/Problem/newEdiTest.edi", Overwrite)

# FileExistsAsync("/newEdiTest.edi")
Command:  TYPE I
Response: 200 Type set to I
Command:  SIZE /newEdiTest.edi
Response: 550 /newEdiTest.edi: Operation not permitted

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

**Comment by robinrodricks** [comment]
Please add a new issue for this.

**Comment by patzila** [comment]
Create new issue here https://github.com/robinrodricks/FluentFTP/issues/518

**Comment by fernandoRSS** [comment]
I have the same issue with version 32.4.1 but with the version 17.5.8 it works properly.
